"""Description of migration

Revision ID: a98befbfdc39
Revises: 
Create Date: 2023-05-22 16:19:39.998362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98befbfdc39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('student_name', sa.String(length=100), nullable=True))
        batch_op.add_column(
            sa.Column('matric_no', sa.String(length=50), nullable=True))

    with op.batch_alter_table('lecturer', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('department', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturer', schema=None) as batch_op:
        batch_op.drop_column('department')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('matric_no')
        batch_op.drop_column('student_name')

    # ### end Alembic commands ###
